version: '3'

services:

  # Use root/example as user/password credentials
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    tty: true
    stdin_open: true

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    links:
     - db
     
  smarthome:
    build: ./smarthomeDocker
    container_name: smarthomeDocker
    ports:
    - 8080:8080
    restart: always
    links:
      - db
#  web:
#    image: nginx
#    volumes:
#      - ./nginx/templates:/etc/nginx/templates
#      - ./nginx/web:/usr/share/nginx/html
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80
#    links:
#      - db
