version: '3'

services:
  smarthome:
  build: ./smarthomeDocker
  container_name: smarthomeDocker
  ports:
  - 8080:8080
  restart: always
    #links:
     # - db

#  web:
#    image: nginx
#    volumes:
#      - ./nginx/templates:/etc/nginx/templates
#      - ./nginx/web:/usr/share/nginx/html
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80
